services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Maps host port (APP_HOST_PORT, default 5000) to container port (FLASK_RUN_PORT, default 5000)
      - "${APP_HOST_PORT:-5000}:${FLASK_RUN_PORT:-5000}"
    volumes:
      # Make sure the host path '/mnt/user/appdata/avnupdatechecker/data' exists on your Unraid system.
      # The container path '/data' must remain, as the app expects it.
      - /mnt/user/appdata/avncodex-dev/data:/data
    environment:
      # FLASK_RUN_PORT tells the app inside the container which port to listen on.
      # Dockerfile provides a build-time default. This allows runtime override via .env file or environment.
      # It's also used for the container side of the port mapping above.
      - FLASK_RUN_PORT=${FLASK_RUN_PORT:-5000}
      - PUID=99  # Typically 'nobody' user on Unraid
      - PGID=100 # Typically 'users' group on Unraid
    restart: unless-stopped
# No named volumes needed for this Unraid-specific configuration 