services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000" # Users might change the host port (left side) on Unraid to avoid conflicts
    volumes:
      # Make sure the host path '/mnt/user/appdata/avnupdatechecker/data' exists on your Unraid system.
      # The container path '/data' must remain, as the app expects it.
      - /mnt/user/appdata/avncodex-dev/data:/data 
    environment:
      - PUID=99  # Typically 'nobody' user on Unraid
      - PGID=100 # Typically 'users' group on Unraid
    restart: unless-stopped

# No named volumes needed for this Unraid-specific configuration 